<a href="https://colab.research.google.com/github/sumits-14/Data_Science/blob/main/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# Create 4x4 array of all True values
np.full((4,4),True)   # with full
#np.ones((4,4),dtype=bool)  # with ones

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
# Create 4x4 array of all False values
np.full((4,4),False) #with full
#np.zeros((4,4),dtype=bool) #with zeros

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# Create 4x4 array of Digonal elements as 1's and Non diagonal elements as 0's
np.diag(np.ones(4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#Create 4x4 array of Digonal elements as True and Non diagonal elements as False
np.diag(np.ones(4,dtype=bool))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [ ]:
# Create 4x4 array of Digonal elements as False and Non diagonal elements as True
~np.diag(np.ones(4,dtype=bool))


array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [ ]:
#Create 2D and 3D arrays of 1's
np.ones((3,4)) #2D of 1's

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones((2,3,2)) #3D of 1's

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

## **Difference of list and numpy array:**

**List:**

-list is built in datatype

-list are mutable

-list use []

-list support indexing and slicing.

-list can be homogeneous or heterogeneous

**Numpy Array:**

-Numpy is external library

-Numpy array are mutable

-Numpy array use []

-Numpy array support indexing and slicing.

-Numpy array store homogeneous data

