<a href="https://colab.research.google.com/github/sumits-14/Data_Science/blob/main/NumpyAssignment02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
# 1. Create 4x4 array of all True values
s1 = np.ones((4, 4), dtype=int)
print(s1)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
s2 = np.full((4, 4), 1, dtype=bool)
print(s2)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [ ]:
# 2. Create 4x4 array of all False values
s3 = np.full((4, 4), 0, dtype=bool)
print(s3)

[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]


In [ ]:
s31 = np.full((4,4), "False")
print(s31)

[['False' 'False' 'False' 'False']
 ['False' 'False' 'False' 'False']
 ['False' 'False' 'False' 'False']
 ['False' 'False' 'False' 'False']]


In [ ]:
# 3. Create 4x4 array of Digonal elements as 1's and Non diagonal elements as 0's
s4 = np.eye(4, dtype=int)
print(s4)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
s5 = np.identity(4, dtype=int)
print(s5)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
# 4.Create 4x4 array of Digonal elements as True and Non diagonal elements as False
s6 = np.eye(4, dtype=bool)
print(s6)

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]


In [ ]:
s7 = np.identity(4, dtype=bool)
print(s7)

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]


In [ ]:
# 5.Create 4x4 array of Digonal elements as False and Non diagonal elements as True
s8 = ~np.eye(4, dtype=bool)
print(s8)

[[False  True  True  True]
 [ True False  True  True]
 [ True  True False  True]
 [ True  True  True False]]


In [ ]:
s9 = ~np.identity(4, dtype=bool)
print(s9)

[[False  True  True  True]
 [ True False  True  True]
 [ True  True False  True]
 [ True  True  True False]]


**Difference of list and numpy array**
->